#%RAML 0.8
title: Pensive API
version: v1
baseUri: https://api.pensive.com/
mediaType: application/json

#schemas:
#  - author: !include author.schema
#
#resourceTypes:
#  - collection:
#      description: Collection of available <<resourcePathName>> in Jukebox.
#      get:
#        description: Get a list of <<resourcePathName>>.
#        responses:
#          200:
#            body:
#              application/json:
#                example: |
#                  <<exampleCollection>>
#      post:
#        description: |
#          Add a new <<resourcePathName|!singularize>> to Jukebox.
#        body:
#          application/json:
#            schema: <<resourcePathName|!singularize>>
#            example: |
#              <<exampleItem>>
#        responses:
#          200:
#            body:
#              application/json:
#                example: |
#                  { "message": "The <<resourcePathName|!singularize>> has been properly entered" }
#
#
#  - collection-item:
#      description: Entity representing a <<resourcePathName|!singularize>>
#      get:
#        description: |
#          Get the <<resourcePathName|!singularize>>
#          with <<resourcePathName|!singularize>>Id =
#          {<<resourcePathName|!singularize>>Id}
#        responses:
#          200:
#            body:
#              application/json:
#                example: |
#                  <<exampleItem>>
#          404:
#            body:
#              application/json:
#                example: |
#                  {"message": "<<resourcePathName|!singularize>> not found" }
#
#
#      put:
#        description: <<resourcePathName|!singularize>> edited.
#        body:
#          application/json:
#            schema:
#
#        responses:
#          200:
#            body:
#              application/json:
#      delete:
#        description: <<resourcePathName|!singularize>> deleted.
#        responses:
#          204:

/authors:
  get:
    body:
      application/json:
        example: !include authors-collection.json
  post:
    body:
      application/json:
        schema: !include author.schema
        example: !include author-item.json
    responses:
      200:
        body:
          application/json:
            example: !include author-item.json

  /{authorName}:
    delete:

/users:
  get:
  post:

  /{userId}:
    delete:

    /books:
      get:
      post:

      /{bookName}:
        delete:

/books:
  get:
  post:

  /{bookName}:
    delete:

    /chapters:
      get:
      post:

      /{chapterTitle}:
        delete:

        /paragraphs:
          get:
          post:

          /{paragraphId}:
            put:
            delete:

/notes:
  get:
  post:

  /{noteId}:
    put:
    delete:

/comments:
  get:
  post:

  /{commentId}:
  put:
  delete: